namespace CocoaderWRC
{
	runtimeclass Cocoader
	{
		Cocoader();

		// Methods to expose
		void InitializeCocoader(String url);
		Windows.Foundation.IAsyncAction StartStreamingAsync();
		Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVector<Windows.Graphics.Imaging.SoftwareBitmap>> GetNextFrameAsync();
		void Decode();
	};
}
